version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: pip install --upgrade pip --user
      - run: pip install -r ~/code/ProductDetectionShopee/requirements.txt --user
